### ISSUE TITLE
First Suggestion 

### ISSUE THREAD

**Issue by Caioz10** [epic-hacks/epic-hacks-surviv.io#15]
Can we get AutoPunch Like IceHacks? 

Yes, you know why I am talking this, because I saw a hacker then he was following me and punching me! I really need this cuz its soo coolllllll and I really wanna it on EpicHacks! 

Imagine a hacker killing a hacker

this is the end of da suggestion

**Comment by Caioz10** [comment]
"𝟎 𝐜𝐨𝐦𝐦𝐞𝐧𝐭𝐬"

**Comment by epic-hacks** [comment]
We aren't planning to make an autoattack cheat, but instead, i all goes well, we will release anit-autoattack, which will detect cheaters that follow you, take control over the inputs and kill them before they kill you

**Comment by Caioz10** [comment]
oK
