### ISSUE TITLE
Aim Bot update today

### ISSUE THREAD

**Issue by epic-hacks** [epic-hacks/epic-hacks-surviv.io#5]
If you saw, the current aim bot pretty often falls behind the enemy during his movement. No worries, I'm aware of that and that happens because of the current compilation settings which reduces the performance.

We created the math in the way that aimbot should shoots directly at the player regardless of how fast he moves. We are taking into account the distance, the bullet speed, the vector of movement of both player and enemy, even the survivs' lags. So you deserve to see the whole power of it!

I'll fix that today. Stay tuned

**Comment by epic-hacks** [comment]
Update is ready, enjoy the aim!

**Comment by riverzhao7** [comment]
Thanks you can do the same thing with gernade I think so that it never misses :)
