### ISSUE TITLE
Wont work

### ISSUE THREAD

**Issue by GucciGamerXD** [epic-hacks/epic-hacks-surviv.io#8]
i did what you said and i downloaded it and it says read only then i upload it and i cant click it to upload it

**Comment by epic-hacks** [comment]
You have an issue with downloading and installing the cheat?

**Comment by GucciGamerXD** [comment]
yes

**Comment by GucciGamerXD** [comment]
both so now what?

**Comment by epic-hacks** [comment]
Go to the [download page](https://github.com/epic-hacks/epic-hacks-surviv.io/releases/tag/v1.1.0), under assets click __EPIC-HACKS.v1.1.0.surviv.io.zip__ and the cheat would be downloaded. Then unzip the downloaded file, go to Chrome -> settings -> more tools -> extensions, turn on __developer mode__ on the top right corner, then on the top left corner press __load unpacked__ and select unzipped folder. It should work fine.

**Comment by GucciGamerXD** [comment]
i do and then when u go to load unpacked all of the downloads are grey and i can't click them to load them

**Comment by epic-hacks** [comment]
Make sure that you extracted everything from zip file into folder. Inside that folder you should have file __manifest.json__, in load unpacked you should select that folder (which has manifest file inside)

**Comment by GucciGamerXD** [comment]
i dont have that

**Comment by epic-hacks** [comment]
[EPIC-HACKS.v1.1.0.surviv.io.zip](https://github.com/epic-hacks/epic-hacks-surviv.io/files/4708441/EPIC-HACKS.v1.1.0.surviv.io.zip)
unzip that file and select the unzipped folder in load unpacked.

**Comment by GucciGamerXD** [comment]
how do i unzip it

**Comment by GucciGamerXD** [comment]
or how do i extract everything from the json thing

**Comment by epic-hacks** [comment]
download _7zip_ if you are using Windows, or _The Unarchiver_ if you are using MacOS.
Then using one of those unzip the file I attached above and select the resulting folder

**Comment by GucciGamerXD** [comment]
im using chromebook do u have discord so i can show u the pic

**Comment by epic-hacks** [comment]
https://www.businessinsider.com/how-to-unzip-files-on-chromebook

**Comment by GucciGamerXD** [comment]
still doesnt work do u have instagram or anything i can put a picture?

**Comment by epic-hacks** [comment]
you can make a screenshot on your chromebook and attach it here

**Comment by GucciGamerXD** [comment]
how?

**Comment by epic-hacks** [comment]
idk how do you make screenshot there, but to attach it, just simply drag and drop it here in the textfield

**Comment by GucciGamerXD** [comment]
![Screenshot 2020-05-31 at 1 52 55 PM](https://user-images.githubusercontent.com/66223181/83362995-acc94380-a34a-11ea-9b12-c46b14e065b0.png)

**Comment by GucciGamerXD** [comment]
![Screenshot 2020-05-31 at 2 26 32 PM](https://user-images.githubusercontent.com/66223181/83363018-cc606c00-a34a-11ea-9613-afb4bcdb21c5.png)

**Comment by epic-hacks** [comment]
right, you have only zip files there. You need to extract __everything__ from zip file firstly and only then select the folder with ALL extracted files

**Comment by GucciGamerXD** [comment]
i did

**Comment by GucciGamerXD** [comment]
can u make like a video

**Comment by epic-hacks** [comment]
idk how to extract files from zip on chromebook. I've never used it. Follow any guide on the web on how to extract the files

**Comment by GucciGamerXD** [comment]
i did and then did exactly what it said and i still can do it

**Comment by epic-hacks** [comment]
then idk how to help you

**Comment by GucciGamerXD** [comment]
ok then nvr sorry for waisting your time

**Comment by epic-hacks** [comment]
sorry that i wasn't able to help. Try to follow any guides on the web on how to install custom extension

**Comment by GucciGamerXD** [comment]
do i have to have the surviv exstition first?

**Comment by epic-hacks** [comment]
no. Surviv has no extensions. the only thing you need to install is cheat
