### ISSUE TITLE
Cant signin 

### ISSUE THREAD

**Issue by Survivmasrere** [epic-hacks/epic-hacks-surviv.io#9]
pls help, i cant sign in

**Comment by epic-hacks** [comment]
What is the issue? Why?

**Comment by umarkhan852** [comment]
Very Bad Aimbot
Ice hack Have very Great Aimbot
Pls Fix Aimbot
means Auto aimbot

**Comment by umarkhan852** [comment]
Iam The Bigeest Pro Hacker of Asia My Name Is [AU] Rajpoot 
Iam Sorry Your Hacker Is Very Good Bro Nice Aimbot Thnx Bro 
And I Got 20 Kills With This Hack Thnx Again
![try](https://user-images.githubusercontent.com/59364343/83501445-8d145580-a4d9-11ea-9af6-6d30433bd86b.PNG)

**Comment by epic-hacks** [comment]
@umarkhan852 Thank you for your feedback! Trying our best to provide epic-hackers with the best game experience!
